workspace:
  base: /test
  path: oe_multilingual

services:

  web:
    image: fpfis/httpd-php-dev:7.1
    environment:
     - DOCUMENT_ROOT=/test/oe_multilingual

  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  frpc-tunnel:
    image: fpfis/drone-frpc-plugin:latest
    when:
      event: [ push, tag ]
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=oe_multilingual-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/oe_multilingual/.frpc

matrix:
  DRUPAL_VERSION:
    - 8.6.x

pipeline:

  composer-install:
    image: fpfis/httpd-php-dev:7.1
    volumes:
      - /cache:/cache
    commands:
      - composer require --dev webflo/drupal-core-require-dev:${DRUPAL_VERSION=8.6.x}

  site-install:
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-dev:7.1
    commands:
      - ./vendor/bin/behat
