language.entity.*.third_party.oe_multilingual:
  type: mapping
  label: 'OpenEuropa Multilingual extra settings on languages'
  mapping:
    native_language:
      type: text
      label: 'Native language title'
    weight:
      type: integer
      label: 'Weight'