oe_multilingual.settings:
  type: mapping
  label: 'Language category'
  mapping:
    category:
      type: string
      label: 'The category of the language.'

language.entity.*.third_party.oe_multilingual:
  type: oe_multilingual.settings
